version: '3.4'

services:
  opentelemvcwebapp:
    image: ${DOCKER_REGISTRY-}opentelemvcwebapp
    build:
      context: .
      dockerfile: OpenteleMvcWebApp/Dockerfile

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
     - "9411:9411"
  
  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
     - ./temp/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
     - "13133:13133"
     - "9411"
     - "4317:4317"

